development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: assessment_dev
  pool: 5
  host: 127.0.0.1
  username: root
  password: ""
  # socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: assessment
  pool: 5
  username: root
  password: ""


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: assessment_test
  pool: 5
  username: root
  password: ""
